os: linux

services:
  - docker

language: node_js

node_js:
  - "14"

cache:
  directories:
    - node_modules
    - client/node_modules
    - server/node_modules

install:
  - npm i
  - cd $TRAVIS_BUILD_DIR/

before_script:
  - npm run dependencyCheck

script:
  - npm test
  - npm run build

# --all-tags was introduced in version v20.10, older versions pushed all images automatically if no tag was provided
after_success:
 - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
   docker -v;
   echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
   docker image push --all-tags "${DOCKER_USERNAME}/poinz" || docker image push "${DOCKER_USERNAME}/poinz";
   fi
